### ISSUE TITLE
Kindly include Profile Picture

### ISSUE THREAD

**Issue by karmecdo** [zakee94/online-banking-system#2]
1). Please kindly include **'Profile picture'** to the banking system
2). it is not registering new user to the database, it returns _successful_ after sending the registration form but new customer added to the database, only the pre-registered customers are in the database.
3. it will be great if there could be in 3 category "Admin", "Staff" and  "Customer" on like the 2 category that it is, my reason: not all staff should access to the admin of a banking system, so the Admin will manage the staffs and customers while staffs will manage customers only.

**Comment by zakee94** [comment]
Try using the console to insert a new tuple/row into the customer table. Does it happen ?

**Comment by karmecdo** [comment]
yes i did that, with that i was able to add new customer, but after login the account details didnt show in the right hand-side column.

**Comment by karmecdo** [comment]
3). **it will be great if there could be in 3 category "Admin", "Staff" and "Customer" on like the 2 category that it is, my reason: not all staff should access to the admin of a banking system, so the Admin will manage the staffs and customers while staffs will manage customers only.**

**Comment by ghentledeveloper** [comment]
I logged in the user with the password nafees123 but the sidebar transfer didn't href and other articles at the nav bar isn't linking, what did I wrong?

**Comment by zakee94** [comment]
Can you please be a bit more specific ? What do mean by sidebar transfer ?

**Comment by ghentledeveloper** [comment]
The nav bar when you login a client that has home, transfer funds,
beneficiary and complaint. When clicked on will prompt error message: page
not found.

If you could rectify the error and send me the file I'll appreciate even
the admin login is unresponsive. No href is working at all. I tried editing
the customer_account file but couldn't see the info I saw from the front
end.
Pls debug or troubleshoot the error and get back to me.

Thanks

**Comment by ghentledeveloper** [comment]
I think I fixed some of them but the admin login isn't responding. Anything
to do? I use Xampp
Thanks

**Comment by CommanderShepard-sys** [comment]
I do not have any complaints or issues, I just stopped to say hello and thanks. Your program is working like a charm. Thank you for sharing source code with students like me. I am still learning to code in PHP and JavaScript and it means a lot to me.
Of course, this is a homework of yours, I suppose, and everything is so simple, graphical design is eye candy, but there is always a space for improvement. If you love to be cooperative, and you are not just a hobbyist I am interesting to learn from you how to be a better coder and also have some ideas how this project can be improved and how to look like 100% professional product. Cheers

**Comment by zakee94** [comment]
Hey @CommanderShepard-sys , glad you like this program!
However this tech stack has become old/limited. Professional websites these days are built using Angular, Express, NodeJS as frontend and MongoDB/MariaDB, Java, Python, MySQL etc.
I suggest you learn MEAN/MERN stack. 
These stacks are generally coupled with Apache servers using springboot, kafka, etc.
Becoming a good coder requires practice and apart from side projects like these, try brushing up your algorithmic skills and problem solving ability. That is more important than learning tech stacks.
Try solving problems on topcoder, codechef, etc and keep practicing.

Cheers,
Garrus Valkarian ;)
